### ISSUE TITLE
Add caching to goa backend

### ISSUE THREAD

**Issue by erichartline** [dictybase-playground/kubeless-nodefn#1]
See https://github.com/dictyBase/Genomepage/issues/35

**Comment by erichartline** [comment]
https://medium.com/ibm-watson-data-lab/building-an-api-cache-with-redis-and-node-3fbad5675d5d
https://www.compose.com/articles/api-caching-with-redis-and-nodejs/

**Comment by cybersiddhu** [comment]
The caching method still need to be refactored. The redis caching **should be set** around or after this [line](https://github.com/dictybase-playground/kubeless-nodefn/blob/master/gene/handler.js#L63) in `handler.js`. The redis `get` and `set` code *should* be paired and follow each other, they *should* not written separately that are lines apart. This allow to maintain the atomicity of caching or in other words you should retrieve and store the identical data from the cache. Intervening code between `get` and `set` actions might break that concept. 
So, remove the `redis set` caching lines from `api.js` and put them in `handler.js` instead right after `get` lines.

**Comment by erichartline** [comment]
This has been fixed and pushed into `master`.
