### ISSUE TITLE
Separate functions

### ISSUE THREAD

**Issue by cybersiddhu** [dictybase-playground/kubeless-nodefn#2]
https://github.com/dictybase-playground/kubeless-nodefn/blob/6663c26d3b535e8b6ca89847e65fbafdd538aa21/geneids/handler.js#L181

You need to have separate functions for GET and POST requests, one function serves only one type of requests.

**Comment by erichartline** [comment]
These have been separated into different functions -- `cachefn` for POST, `gene2namefn` for GET.
