### ISSUE TITLE
reading file line by line

### ISSUE THREAD

**Issue by cybersiddhu** [dictybase-playground/kubeless-nodefn#3]
https://github.com/dictybase-playground/kubeless-nodefn/blob/6663c26d3b535e8b6ca89847e65fbafdd538aa21/geneids/handler.js#L86

__Do__ read file line by line, do not read it all in the memory, that approach is not deployable in production.

**Comment by cybersiddhu** [comment]
How to read a gff3 file using nodejs https://github.com/bionode/bionode-gff/blob/master/lib/gff.js
It reads it line by line as emits event on reading every line of feature. Walk back to the frontpage of this repo to read the api. You could copy this module in your project or use it as a library or learn from it to modify your code.

**Comment by erichartline** [comment]
I used the `bionode-gff` library to simplify the process.
