### ISSUE TITLE
Accept env variable for cache length of stay

### ISSUE THREAD

**Issue by erichartline** [dictybase-playground/kubeless-nodefn#6]
Keep default as 15 days, but if there is an ENV then use that for the time

**Comment by cybersiddhu** [comment]
The use of this `env` variable has to be added to the documentation.

**Comment by erichartline** [comment]
I had made note of `REDIS_CACHE_EXPIRATION` in the [README](https://github.com/dictybase-playground/kubeless-nodefn/blob/master/gene/README.md). I added a more detailed example today that also clarifies the expiration is accepted as number of days (rather than seconds, which the user shouldn't have to convert manually).
