### ISSUE TITLE
All uniprot ids are not getting loaded

### ISSUE THREAD

**Issue by cybersiddhu** [dictybase-playground/kubeless-nodefn#7]
It seems the function is not mapping all uniprot ids from `dicty.txt` file. Here is a redis session to show that
```
redis-cli -h ${REDIS_MASTER_SERVICE_HOST}
10.109.46.14:6379> HGETALL UNIPROT2NAME/uniprot
 1) "Q23911"
 2) "29C"
 3) "Q54P77"
 4) "4cl1"
 5) "Q54P78"
 6) "4cl2"
 7) "Q54P79"
 8) "4cl3"
 9) "Q54N73"
10) "7tmk1"
11) "Q54U65"
12) "7tmk2"
13) "P14196"
14) "AAC11"
15) "P14195"
16) "AAC1"
17) "P14197"
18) "AAC3"
19) "P14198"
20) "AAC4"

10.109.46.14:6379> HLEN UNIPROT2NAME/uniprot
(integer) 10
```
In contrast this is the gene id mapping.
```
10.109.46.14:6379> HLEN GENE2NAME/geneids
(integer) 12260
```

I believe there should be more entries tied to that **uniprot** hash key in the redis. So,
* Investigate the issue.
* Fix the issue.
* Write an explanation in the comment below about how the issue might have appeared and eventually got fixed. 
* Verify and show(snapshot or count through a script) that all expected entries gets persisted in the redis.

**Comment by erichartline** [comment]
I have not been able to replicate this bug. Here's my exact process in deploying this function:

1) Run through the [pre-deploy setup](https://github.com/dictybase-playground/kubeless-nodefn/tree/master/uniprot) to get `dicty.txt` in local minio.
2) Zip all JS files in the repo's `uniprot` directory:
`zip uniprot.zip *.js`
3) Deploy the function:
`kubeless function deploy uniprotcachefn --runtime nodejs8 --from-file uniprot.zip --handler handler.txt2redis --dependencies package.json -e MINIO_ACCESS_KEY=XXX -e MINIO_SECRET_KEY=XXX --namespace dictybase`
4) Add kubeless trigger:
`kubeless trigger http create uniprotcachefn --function-name uniprotcachefn --hostname betafunc.dictybase.local --tls-secret dictybase-local-tls --namespace dictybase --path geneids/ucache`
5) Make POST request:
`curl -k -X POST https://betafunc.dictybase.local/geneids/ucache -H 'Content-Type: application/json' -d @metadata.json`

Here is my `metadata.json`:
```
{
  "bucket": "uniprot",
  "file": "dicty.txt"
}
```

Doing all this produces the following from my Redis session:
```
redis-master:6379> HLEN UNIPROT2NAME/uniprot
(integer) 4140
```

**Comment by cybersiddhu** [comment]
Maybe upload the dicty.txt file in this issue. I can give it another shot.
