### ISSUE TITLE
Accessing genomepage by gene name

### ISSUE THREAD

**Issue by cybersiddhu** [dictybase-playground/kubeless-nodefn#8]
As i discussed briefly in our slack chat, here will be the approach
1. Storing the map from gff3 file.
It should go in the geneids function where the map between the gene identifier -> gene name is stored. All is needed is to store the reverse mapping. The following line should work.
 ```redisClient.hset(hash,feature.attributes.Name, feature.attributes.ID)```
2. Creating backend endpoint.
It should reside in `geneids` kubeless function, in fact this nodejs function https://github.com/dictybase-playground/kubeless-nodefn/blob/master/geneids/handler.js#L130 can be reused. All it has to do is to serve the mapping in reverse(gene name -> identifier). Then add an http trigger(ingress) to get the conversion, use `/conversion/genenames/{name}` or `/conversion/names/{name}` for the http get path.
Make sure to update the documentation accordingly.
3. Frontend route.
The existing routing should use [regexp](https://reacttraining.com/web/api/Route/path-string) in react-router match either of an identifier or gene name. The gene identifier match goes first and  goes to the name match as a failover. It's preferable to have separate react-components for the matches. The dictybase gene identifiers should be matched with a regex. The regex should match gene identifiers for all organisms and **should not be hard coded only for *D.discoideum* identifier**. We have more than one organisms in our database and we are going to add more, so *hard coding is not a choice*.
The gene identifier match goes to existing component whereas the name match goes to a component that do fetch request to the backend(no. 2), gets the identifier and route to the default path with identifier. In case of no match from the backend route it to a error page with proper message.

**Comment by erichartline** [comment]
Updating steps based on our discussion:

1. Same as above, this is already complete.
2. Add one more `regex` route to the function (`/genes/name/${name}`). Use the cache to convert it to gene ID, then return the same JSON structure. Update the documentation.
3. Use regexp with react-router to detect id or name, then call the appropriate backend. No extra fetches.
